# 是否启用SpringDoc的API文档功能
springdoc.api-docs.enabled=false

# 指定需要生成API文档的路径匹配模式
springdoc.pathsToMatch=/v1/**,/session/**,/dashboard/**,/system/**,/user/**

# 是否启用Swagger UI界面
springdoc.swagger-ui.enabled=false

# Swagger UI中操作列表的排序方式，alpha表示按字母顺序排序
springdoc.swagger-ui.operationsSorter=alpha

# Swagger UI中标签列表的排序方式，alpha表示按字母顺序排序
springdoc.swagger-ui.tagsSorter=alpha

# Higress控制台的构建版本号，通过Maven插件自动替换
higress-console.build.version=@app.build.version@

# Higress控制台的开发模式标识，通过Maven插件自动替换
higress-console.build.dev=@app.build.dev@

# 是否启用HTTP响应压缩功能
server.compression.enabled=true

# 启用压缩的MIME类型列表
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript

# 启用压缩的最小响应大小阈值（字节），此处设置为2KB
server.compression.min-response-size=2048

# 需要排除在压缩之外的用户代理列表
server.compression.excluded-user-agents=MSIE 6.0,UCBrowser

# 控制台日志输出格式配置
# %clr 表示颜色格式化
# %d 表示日期时间
# %p 表示日志级别
# %t 表示线程名
# %logger 表示记录器名称
# %mdc 表示映射诊断上下文
# %m 表示日志消息
# %n 表示换行符
# %wEx 表示异常堆栈信息
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(70396){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} {%mdc} %clr(:){faint} %m%n%wEx


higress-console.kube.config=G:\\BaiduSyncdisk\\CS\\higress-console-main\\backend\\console\\src\\main\\resources\\config
higress-console.controller.access-token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImowLUZwZWZFa1ZjbmRsTUcySGMzbXM2SHR1VFM1emktTGx4X0tzMlpOTUkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJoaWdyZXNzLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJoaWdyZXNzLWNvbnNvbGUtdG9rZW4tN2x2bXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiaGlncmVzcy1jb25zb2xlIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMjM1YThiOWYtZWVhMC00YjJkLWE4NmMtN2JhOWNmNDg4OGUwIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmhpZ3Jlc3Mtc3lzdGVtOmhpZ3Jlc3MtY29uc29sZSJ9.GIUrMftswdLArqaBDNgkO6v_UjQbhIX2TTPi02SWe_2zT8KK03jxXozE4J335g4o2WpjVphj8xsSDkWPU8JyGMBQgPAzcPuKnwhhEPCHhDSqKeplzXL_gsDyXjkSj20faT5zNxB6Y8_4dP7_FuvAYamhQzN0rvLjiX1nmHC3L18-1ilhukiknj4sRPsBvJfPnrLtIyjH3gIrWz0-TN_EM1fFMlz1JDhHyTdh9b96LThCfgpYVm1b2yh_u455UGj1eg1X5M7lTwkwT_xeAKBpzOZIbb7PocGhz5lfhxfgxduQVffbokWddOouasPw5bqTHSNEhsvbVm_m8bnoEFy7VA
